#秘钥生成命令   keytool -genkey -alias tomcat -keypass guiyuoneiros_pd#_666 -keyalg RSA -keysize 2048 -validity 365 -storetype PKCS12 -keystore D:/tomcat.keystore -storepass guiyuoneiros_pd#_666 -dname "CN=localhost,OU=zero,O=zero,L=beijing,S=beijing,C=cn"
server:
  port: 8443
  servlet:
    context-path: /app
  ssl:
    key-store: classpath:server/tomcat.keystore    #秘钥证书库文件所在位置
    key-store-password: guiyuoneiros_pd#_666       #秘钥
    key-store-type: PKCS12                         #类型
    key-alias: tomcat                              #别名条目

http:
  port: 8080  #http端口

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml 指定全局配置文件的位置
#  mapper-locations: classpath:mybatis/mapper/*.xml  指定sql映射文件的位置